### ISSUE TITLE
Add support for displaying tabs as four spaces in code preview?

### ISSUE THREAD

**Issue by Jont828** [atom-community/markdown-preview-plus#435]
Could you add support to display tabs as four spaces in the code preview sections? Right now, it's displaying as 2 spaces.

**Comment by lierdakil** [comment]
Thanks for reporting. Should be fixed in v3.7.0 (will use Atom setting by default, can be overridden in package settings)

**Comment by shortda** [comment]
This is still an issue with package version 3.9.3 on windows 10. The preview renders a 1-3 space indent as a list, but with 4 or more spaces it displays the list marker and text inline with the text above the list.
